# lang.py
LANGUAGES = {
    'window_title': { 'en': 'SpotiDown', 'bg': 'SpotiDown', 'es': 'SpotiDown' },
    'url_label': { 'en': 'URL (Spotify or Apple Music):', 'bg': 'URL (Spotify или Apple Music):', 'es': 'URL (Spotify o Apple Music):' },
    'start_button': { 'en': 'Start Download', 'bg': 'Старт', 'es': 'Iniciar Descarga' },
    'progress_label': { 'en': 'Log:', 'bg': 'Прогрес:', 'es': 'Registro:' },
    'lang_label': { 'en': 'Language:', 'bg': 'Език:', 'es': 'Idioma:' },
    'source_type_label': { 'en': 'Source Type:', 'bg': 'Тип на източника:', 'es': 'Tipo de Fuente:' },
    'download_folder_label': { 'en': 'Download Folder:', 'bg': 'Папка за сваляне:', 'es': 'Carpeta de Descarga:' },
    'browse_button': { 'en': 'Browse...', 'bg': 'Избери...', 'es': 'Explorar...' },
    'keys_prompt_title': { 'en': 'API Keys Required', 'bg': 'Необходими са API Ключове', 'es': 'Se Requieren Claves de API' },
    'keys_prompt_message': {
        'en': 'Please enter your API keys. Genius.com key is optional.',
        'bg': 'Моля, въведете вашите API ключове. Ключът за Genius.com не е задължителен.',
        'es': 'Por favor, ingrese sus claves de API. La clave de Genius.com es opcional.'
    },
    'save_keys_button': { 'en': 'Save and Continue', 'bg': 'Запази и Продължи', 'es': 'Guardar y Continuar' },
    'settings_menu_label': { 'en': 'Settings', 'bg': 'Настройки', 'es': 'Configuración' },
    'settings_menu_change_keys': { 'en': 'Change API Keys', 'bg': 'Смяна на API Ключове', 'es': 'Cambiar Claves de API' },
    'quality_label': { 'en': 'Audio Quality (kbps):', 'bg': 'Качество на звука (kbps):', 'es': 'Calidad de Audio (kbps):' },
    'cancel_button': { 'en': 'Cancel', 'bg': 'Отказ', 'es': 'Cancelar' },
    'cancelling_message': { 'en': 'Cancelling... will stop after the current song.', 'bg': 'Отменя се... ще спре след текущата песен.', 'es': 'Cancelando... se detendrá después de la canción actual.' },
    'downloading_song': { 'en': 'Downloading:', 'bg': 'Сваля се:', 'es': 'Descargando:' },
    'song_done': { 'en': '✓ Done:', 'bg': '✓ Готово:', 'es': '✓ Hecho:' },
    'song_skipped': { 'en': '→ Skipped (file already exists):', 'bg': '→ Пропуснато (файлът вече съществува):', 'es': '→ Omitido (el archivo ya existe):' },
    'process_finished': { 'en': '\n--- Finished! ---', 'bg': '\n--- Процесът приключи! ---', 'es': '\n--- ¡Proceso Terminado! ---' },
    'connecting_spotify': { 'en': 'Connecting to Spotify API...', 'bg': 'Свързване със Spotify API...', 'es': 'Conectando a la API de Spotify...' },
    'connecting_genius': { 'en': 'Connecting to Genius.com API...', 'bg': 'Свързване с Genius.com API...', 'es': 'Conectando a la API de Genius.com...' }
}

def get_string(key, lang_code='en'):
    lang_dict = LANGUAGES.get(key, {})
    return lang_dict.get(lang_code, lang_dict.get('en', f"[{key}]"))
# New UI and download pipeline. Older languages fall back to English per key.
MESSAGES = {
    'subtitle': ('Your music. Complete with artwork.', 'Твоя музыка — вместе с обложками.'),
    'url_label': ('Track or playlist link', 'Ссылка на песню или плейлист'),
    'lang_label': ('Language', 'Язык'),
    'source_type_label': ('Source', 'Источник'),
    'download_folder_label': ('Save music to', 'Папка для музыки'),
    'quality_label': ('MP3 quality · kbps', 'Качество MP3 · кбит/с'),
    'start_button': ('Download music', 'Скачать музыку'),
    'cancel_button': ('Stop', 'Остановить'),
    'browse_button': ('Choose folder', 'Выбрать папку'),
    'settings_menu_change_keys': ('API settings', 'Настройки API'),
    'keys_prompt_title': ('Connection settings', 'Настройки подключения'),
    'keys_prompt_message': ('Spotify Client ID and Secret are needed for Spotify. Genius is optional and is used only for lyrics.', 'Для Spotify нужны Client ID и Client Secret. Genius необязателен и нужен только для текстов песен.'),
    'save_keys_button': ('Save', 'Сохранить'),
    'keys_required': ('Enter Spotify Client ID and Secret in API settings.', 'Введи Spotify Client ID и Client Secret в настройках API.'),
    'lyrics_option': ('Add lyrics (slower)', 'Добавлять тексты песен (дольше)'),
    'strict_hint': ('Strict matching: artist audio sources, version and duration. Uncertain results are skipped.', 'Строгий подбор: аудио исполнителя, версия и длительность. Сомнительные записи пропускаются.'),
    'existing_hint': ('Existing MP3s: artwork update only. To replace an old edit, remove that MP3 or choose a new folder.', 'Старые MP3: только обновление обложек. Чтобы заменить эдит, убери его MP3 из папки или выбери новую папку.'),
    'ready': ('Ready to download', 'Готово к загрузке'),
    'overall': ('Playlist progress', 'Прогресс плейлиста'),
    'progress_label': ('Activity', 'Журнал'),
    'issues_tab': ('Errors and warnings', 'Ошибки и предупреждения'),
    'save_report': ('Save report', 'Сохранить отчёт'),
    'empty_report': ('Errors and warnings will appear here when the download ends.', 'После загрузки здесь появятся все ошибки и предупреждения.'),
    'error': ('Error', 'Ошибка'),
    'warning': ('Warning', 'Предупреждение'),
    'job': ('Download job', 'Загрузка'),
    'reading': ('Reading playlist', 'Читаем плейлист'),
    'searching': ('Finding the original audio', 'Ищем оригинальное аудио'),
    'downloading': ('Downloading audio', 'Скачиваем аудио'),
    'converting': ('Converting to MP3', 'Преобразуем в MP3'),
    'metadata': ('Adding tags and artwork', 'Добавляем теги и обложку'),
    'artwork': ('Artwork', 'Обложка'),
    'lyrics': ('Lyrics', 'Текст песни'),
    'track_finished': ('Track processed', 'Трек обработан'),
    'finished': ('Download finished', 'Загрузка завершена'),
    'finished_issues': ('Finished with errors or warnings', 'Завершено с ошибками или предупреждениями'),
    'cancelled': ('Stopped', 'Остановлено'),
    'cancelling_message': ('Stopping… Waiting for the current operation to finish.', 'Останавливаем… Ждём завершения текущей операции.'),
    'close_running': ('Stop the download and close after the current operation?', 'Остановить загрузку и закрыть окно после текущей операции?'),
    'summary': ('Downloaded: {downloaded} · Updated: {updated} · Skipped: {skipped} · Failed: {failed}', 'Скачано: {downloaded} · Обновлено: {updated} · Пропущено: {skipped} · Ошибок: {failed}'),
    'count_progress': ('Processed {completed} of {total}', 'Обработано {completed} из {total}'),
    'issue_count': ('Errors and warnings: {count}', 'Ошибок и предупреждений: {count}'),
    'track_number': ('Track {number}', 'Трек {number}'),
    'speed_eta': ('{speed:.1f} MB/s · remaining ~{eta}s', '{speed:.1f} МБ/с · осталось ~{eta} с'),
    'no_issues': ('No errors or warnings.', 'Ошибок и предупреждений нет.'),
    'ffmpeg_missing': ('FFmpeg not found. Run start.bat to finish setup.', 'FFmpeg не найден. Запусти start.bat для завершения установки.'),
    'lyrics_disabled': ('Lyrics disabled ({error}). Continuing with audio and artwork.', 'Тексты песен отключены ({error}). Продолжаем загрузку аудио и обложек.'),
    'invalid_source': ('Unsupported source.', 'Источник не поддерживается.'),
    'spotify_url': ('Use a Spotify track or playlist link.', 'Нужна ссылка на трек или плейлист Spotify.'),
    'no_tracks': ('No tracks found. Check the link and access to the playlist.', 'Треки не найдены. Проверь ссылку и доступ к плейлисту.'),
    'unavailable_track': ('Track is unavailable, local or not a music track.', 'Трек недоступен, является локальным файлом или не является песней.'),
    'download_failed': ('Audio download did not produce an MP3 file.', 'Загрузка аудио не создала MP3-файл.'),
    'no_match': ('No reliable original audio found. Track was not downloaded.', 'Надёжное совпадение с оригиналом не найдено. Песня не скачана.'),
    'match_metadata': ('Missing artist or title', 'Нет исполнителя или названия'),
    'match_version': ('Different version / edit', 'Другая версия / эдит'),
    'match_duration_missing': ('Missing duration for verification', 'Нет длительности для проверки'),
    'match_duration': ('Duration differs', 'Длительность отличается'),
    'match_source': ('Not an artist audio source', 'Не аудиозапись с канала исполнителя'),
    'match_title': ('Title differs', 'Название отличается'),
    'candidate_failed': ('Candidate could not be checked: {error}', 'Не удалось проверить вариант: {error}'),
    'selected': ('Selected: {title} · {channel} · {duration}s', 'Выбрано: {title} · {channel} · {duration} с'),
    'existing_audio': ('Updating existing MP3 artwork; its audio is not verified or replaced.', 'Обновляем обложку старого MP3; его аудио не проверяется и не заменяется.'),
    'direct_youtube': ('Direct YouTube mode downloads the chosen video without rejecting edits. Spotify artwork is added only if metadata matches.', 'Режим YouTube скачивает выбранное видео без отсева эдитов. Обложка Spotify добавляется только при совпадении метаданных.'),
    'metadata_kept': ('Audio kept, but metadata could not be saved: {error}', 'Аудио сохранено, но не удалось записать теги: {error}'),
    'no_cover': ('No usable cover. Audio is kept; run the playlist again to retry artwork.', 'Обложка недоступна. Аудио сохранено; запусти плейлист повторно, чтобы добавить обложку.'),
    'cover_error': ('Could not load Spotify artwork: {error}', 'Не удалось получить обложку Spotify: {error}'),
    'no_lyrics': ('Lyrics not found.', 'Текст песни не найден.'),
    'lyrics_error': ('Could not load lyrics: {error}', 'Не удалось загрузить текст песни: {error}'),
    'cover_done': ('Cover embedded for iTunes / iPod.', 'Обложка для iTunes / iPod добавлена.'),
    'song_done': ('Done:', 'Готово:'),
    'connecting_spotify': ('Connecting to Spotify…', 'Подключаемся к Spotify…'),
    'enter_url': ('Paste a track or playlist link first.', 'Сначала вставь ссылку на трек или плейлист.'),
    'report_file': ('Text report', 'Текстовый отчёт'),
    'cut': ('Cut', 'Вырезать'), 'copy': ('Copy', 'Копировать'), 'paste': ('Paste', 'Вставить'),
}
for _key, (_en, _ru) in MESSAGES.items():
    LANGUAGES.setdefault(_key, {}).update(en=_en, ru=_ru)
