"""Conservative metadata matching, not acoustic fingerprint identification."""
import re
import unicodedata
from difflib import SequenceMatcher


def normalize(value):
    return ' '.join(re.findall(r'\w+', unicodedata.normalize('NFKC', value or '').casefold()))


VERSIONS = (
    r'\bsped(?: up)?\b|\bspeed(?: up|ed)?\b|\bускор\w*',
    r'\bslow(?:ed)?\b|\bзамедл\w*', r'\breverb\b', r'\bnightcore\b',
    r'\bedit\b|\bэдит\b', r'\bremix\b|\bремикс\b',
    r'\bcover\b|\bкавер\b', r'\bkaraoke\b|\bкараоке\b',
    r'\blive\b|\bconcert\b|\bконцерт\w*', r'\bacoustic\b|\bакуст\w*',
    r'\binstrumental\b|\bинструментал\w*', r'\bmashup\b',
    r'\b8d\b|\b16d\b|\bbass boosted\b', r'\bremaster\w*',
    r'\bclean\b|\bcensored\b', r'\bextended\b', r'\bloop\b',
)


def version_flags(title):
    return {i for i, pattern in enumerate(VERSIONS) if re.search(pattern, normalize(title))}


def score_candidate(track, video):
    """Return (score, rejection key); zero means do not download this candidate.

    Require an artist-associated audio source and a close duration match. Generic
    fan uploads and music videos may include effects, dialogue or audience noise.
    Channel names are evidence, not proof of authenticity.
    """
    name = normalize(track.get('name'))
    artists = [normalize(a.get('name')) for a in track.get('artists', [])]
    artists = [a for a in artists if a]
    title = normalize(video.get('title'))
    if not name or not artists or not title:
        return 0, 'match_metadata'
    if video.get('is_live') or video.get('live_status') in ('is_live', 'is_upcoming', 'was_live'):
        return 0, 'match_version'
    # Compare qualifiers against the requested track (including official remixes).
    requested_flags = version_flags(name)
    candidate_flags = version_flags(title + ' ' + normalize(video.get('track')))
    if requested_flags != candidate_flags:
        return 0, 'match_version'
    expected = (track.get('duration_ms') or 0) / 1000
    duration = video.get('duration') or 0
    if not expected or not duration:
        return 0, 'match_duration_missing'
    tolerance = min(5, max(2.5, expected * .015))
    if abs(duration - expected) > tolerance:
        return 0, 'match_duration'

    channel = normalize(video.get('channel') or video.get('uploader'))
    channel_base = re.sub(r'\s+(?:topic|official|vevo)$', '', channel)
    artist_channel = any(channel_base == a or channel.replace(' ', '') == a.replace(' ', '') + 'vevo'
                         for a in artists)
    topic = channel.endswith(' topic') and artist_channel
    description = video.get('description') or ''
    generated = 'auto-generated by youtube' in description.casefold()
    official_audio = bool(re.search(r'\b(?:official audio|audio officiel|официальное аудио)\b', title))
    if not artist_channel or not (topic or generated or official_audio):
        return 0, 'match_source'
    if re.search(r'\b(?:music video|official video|видеоклип)\b', title):
        return 0, 'match_source'

    candidate_name = normalize(video.get('track')) or title
    if not video.get('track'):
        # Strip only a leading artist and display labels, never arbitrary brackets.
        for artist in sorted(artists, key=len, reverse=True):
            if candidate_name.startswith(artist + ' '):
                candidate_name = candidate_name[len(artist) + 1:]
        candidate_name = re.sub(r'\b(?:official audio|audio officiel|официальное аудио|official lyric video|lyrics video|lyric video|lyrics|audio|hq|hd|4k)\b', '', candidate_name)
        candidate_name = ' '.join(candidate_name.split())
    similarity = SequenceMatcher(None, name, candidate_name).ratio()
    if similarity < .94:
        return 0, 'match_title'
    return 80 + similarity * 10 + (5 if topic or generated else 0) + 5 * (1 - abs(duration - expected) / tolerance), None
