import copy
import tempfile
import threading
import unittest
from pathlib import Path
from unittest.mock import Mock, patch
from matching import score_candidate
from downloader import DownloaderThread, Cancelled

TRACK = {'id': 'original', 'name': 'A Real Song', 'artists': [{'name': 'The Artist'}],
         'duration_ms': 200000, 'album': {'name': 'Album', 'images': []}}
VIDEO = {'title': 'A Real Song', 'channel': 'The Artist - Topic', 'duration': 200,
         'url': 'https://www.youtube.com/watch?v=original', 'webpage_url': 'https://www.youtube.com/watch?v=original'}


class MatchingTests(unittest.TestCase):
    def test_accepts_topic_audio_and_close_encoder_duration(self):
        self.assertGreater(score_candidate(TRACK, dict(VIDEO, duration=201))[0], 90)

    def test_accepts_artist_official_audio(self):
        video = dict(VIDEO, title='The Artist - A Real Song (Official Audio)', channel='The Artist')
        self.assertGreater(score_candidate(TRACK, video)[0], 0)

    def test_accepts_generated_artist_audio(self):
        video = dict(VIDEO, channel='The Artist', description='Provided to YouTube by Label\nAuto-generated by YouTube.')
        self.assertGreater(score_candidate(TRACK, video)[0], 0)

    def test_rejects_edits_even_at_original_duration(self):
        for suffix in ('sped up', 'slowed reverb', 'nightcore', 'remix', 'edit', 'cover',
                       'караоке', 'ускоренная', 'live', '8D', 'bass boosted', 'instrumental', 'clean'):
            with self.subTest(suffix=suffix):
                self.assertEqual(score_candidate(TRACK, dict(VIDEO, title=VIDEO['title'] + ' ' + suffix))[0], 0)

    def test_rejects_hidden_speed_change_by_duration(self):
        for duration in (180, 220, 0, None):
            self.assertEqual(score_candidate(TRACK, dict(VIDEO, duration=duration))[0], 0)

    def test_rejects_fan_upload_even_with_identical_title_duration(self):
        self.assertEqual(score_candidate(TRACK, dict(VIDEO, channel='Fan music edits'))[0], 0)

    def test_rejects_artist_name_substring_spoof(self):
        self.assertEqual(score_candidate(TRACK, dict(VIDEO, channel='The Artist Fan - Topic'))[0], 0)

    def test_rejects_music_video_with_effects_risk(self):
        self.assertEqual(score_candidate(TRACK, dict(VIDEO, title='The Artist - A Real Song (Official Video)'))[0], 0)

    def test_rejects_other_song_and_live_stream(self):
        self.assertEqual(score_candidate(TRACK, dict(VIDEO, title='A Different Song'))[0], 0)
        self.assertEqual(score_candidate(TRACK, dict(VIDEO, is_live=True))[0], 0)

    def test_preserves_explicitly_requested_remix(self):
        track = dict(TRACK, name='A Real Song (Radio Remix)')
        video = dict(VIDEO, title=track['name'])
        self.assertGreater(score_candidate(track, video)[0], 0)
        self.assertEqual(score_candidate(track, VIDEO)[0], 0)

    def test_russian_title_and_artist(self):
        track = dict(TRACK, name='Песня', artists=[{'name': 'Исполнитель'}])
        video = dict(VIDEO, title='Исполнитель — Песня (Official Audio)', channel='Исполнитель')
        self.assertGreater(score_candidate(track, video)[0], 0)


class JobTests(unittest.TestCase):
    def setUp(self):
        folder = tempfile.TemporaryDirectory()
        self.addCleanup(folder.cleanup)
        self.logs, self.events, self.reports = [], [], []
        self.finish = Mock()
        self.worker = DownloaderThread('https://open.spotify.com/playlist/test', 'spotify', {}, 'ru', self.logs.append,
            self.finish, folder.name, '192', threading.Event(), self.events.append, self.reports.append)

    def test_search_does_not_download_first_edit(self):
        edit = dict(VIDEO, title='A Real Song sped up', url='https://example.test/edit')
        ydl = Mock()
        ydl.extract_info.side_effect = [{'entries': [edit, VIDEO]}, VIDEO]
        with patch('downloader.yt_dlp.YoutubeDL') as factory:
            factory.return_value.__enter__.return_value = ydl
            self.assertEqual(self.worker.select_audio(TRACK), VIDEO['url'])
        self.assertEqual(ydl.extract_info.call_count, 2)
        ydl.download.assert_not_called()

    def test_details_must_pass_even_when_search_result_looks_valid(self):
        ydl = Mock()
        ydl.extract_info.side_effect = [{'entries': [VIDEO]}, dict(VIDEO, duration=180)]
        with patch('downloader.yt_dlp.YoutubeDL') as factory:
            factory.return_value.__enter__.return_value = ydl
            with self.assertRaisesRegex(ValueError, 'не найдено'):
                self.worker.select_audio(TRACK)
        ydl.download.assert_not_called()

    def test_all_failures_accumulated_and_later_tracks_continue(self):
        with patch.object(self.worker, 'select_audio', side_effect=ValueError('No original')) as select:
            self.worker.process_tracks([TRACK, dict(TRACK, name='Next song'), None], '', None)
        self.assertEqual(select.call_count, 2)
        self.assertEqual(self.worker.stats['failed'], 3)
        self.assertEqual(self.worker.stats['completed'], 3)
        self.assertEqual(len(self.worker.issues), 3)
        self.assertEqual(self.events[-1]['completed'], 3)

    def test_summary_after_fatal_error_and_finish_called_once(self):
        with patch('downloader.os.path.exists', return_value=False):
            self.worker.run()
        self.assertEqual(len(self.reports), 1)
        self.assertEqual(len(self.reports[0]['issues']), 1)
        self.assertIn('FFmpeg', self.reports[0]['issues'][0]['message'])
        self.finish.assert_called_once()
        self.assertIn('FFmpeg', self.logs[-1])

    def test_progress_real_percent_speed_and_unknown_size(self):
        self.worker.progress_hook(dict(status='downloading', downloaded_bytes=50, total_bytes=200, speed=1024, eta=4))
        self.assertEqual(self.events[-1]['percent'], 25)
        self.assertEqual(self.events[-1]['speed'], 1024)
        self.worker.last_progress = 0
        self.worker.progress_hook(dict(status='downloading', downloaded_bytes=50))
        self.assertIsNone(self.events[-1]['percent'])
        self.worker.progress_hook(dict(status='finished'))
        self.assertEqual(self.events[-1]['stage'], 'converting')

    def test_cancel_stops_hook_without_marking_track_complete(self):
        self.worker.cancel_event.set()
        with self.assertRaises(Cancelled):
            self.worker.progress_hook(dict(status='downloading'))
        self.worker.run()
        self.assertTrue(self.reports[0]['cancelled'])
        self.assertEqual(self.reports[0]['completed'], 0)
        self.assertEqual(self.reports[0]['issues'], [])

    def test_warnings_are_deduplicated_and_secrets_redacted(self):
        self.worker.keys = {'spotify_secret': 'private-secret'}
        self.worker.warning('failure private-secret')
        self.worker.warning('failure private-secret')
        self.assertEqual(len(self.worker.issues), 1)
        self.assertNotIn('private-secret', str(self.worker.issues) + str(self.logs))

    def test_failed_download_leaves_no_partial_mp3_or_staging_directory(self):
        destination = Path(self.worker.download_path) / 'song.mp3'
        with patch('downloader.yt_dlp.YoutubeDL') as factory:
            def create_partial(*args):
                template = factory.call_args.args[0]['outtmpl']
                Path(template.replace('%(ext)s', 'mp3')).write_bytes(b'broken')
                raise OSError('disconnected')
            factory.return_value.__enter__.return_value.download.side_effect = create_partial
            with self.assertRaises(OSError):
                self.worker.download_audio(VIDEO['url'], str(destination), '')
        self.assertFalse(destination.exists())
        self.assertEqual(list(destination.parent.iterdir()), [])

    def test_metadata_warning_does_not_count_audio_as_failed(self):
        with patch.object(self.worker, 'select_audio', return_value=VIDEO['url']), patch.object(
                self.worker, 'download_audio'), patch.object(self.worker, 'add_metadata', side_effect=OSError('locked')):
            self.worker.process_tracks([TRACK], '', None)
        self.assertEqual(self.worker.stats['downloaded'], 1)
        self.assertEqual(self.worker.stats['failed'], 0)
        self.assertEqual(self.worker.issues[0]['stage'], 'metadata')


if __name__ == '__main__':
    unittest.main()
